[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["../lib", "../node_modules"]
solc_version = "0.8.20"
evm_version = "shanghai"
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
ritual = "https://rpc.ritualfoundation.org"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

